int compturn(int *p, int *trick, int rnd, int start, char who, int *strat, int *a, int *b, int *c);
int debuggingoptions();
int draw(int *deck);
int game(int *n, int *e, int *p, int *w, int *strat, int *trick, int *rnd, char *nname, char *ename, char *pname, char *wname, int *deck, int *pass, int newgame);
int gameOptions(int *n, int *e, int *p, int *w, int *strat, int *trick, int rnd, char *nname, char *ename, char *pname, char *wname, int *deck, int pass);
int getchoice(int *p, int start, int rnd, int *trick, int *strat);
int loadgame(int *n, int *e, int *p, int *w, int *strat, int *trick, int *rnd, char *nname, char *ename, char *pname, char *wname, int *deck, int *pass);
int nosuitsnext(char who, int *strat, int *trick, int suit);
int onlypts(int *p);
int playmax(int *p, int suit, int tmax, char who, int *trick, int start);
int playmaxavg(int *p, char who, int start, int *trick, int rnd, int *strat, int nosuits);
int playmin(int *p, int suit, int max, char who, int *trick, int start, int rnd);
int pointscannotbetaken(int *trick, int suit, int *a, int*b, int *c, int *p);
int ptsintrick(int *t);
int save(int *n, int *e, int *p, int *w, int *strat, int *trick, int rnd, char *nname, char *ename, char *pname, char *wname, int *deck, int pass);
int score(int *n, int *e, int *p, int *w, int *trick, int print);
int start(int *n, int *e, int *p, int *w);
int suitsleft(int *strat, int suit, int who);
int trickmax(int *p, int s);
int trickmin(int *p, int s);
int validtrick(int *p, int card, int start, int rnd);
int won(int *n, int *e, int *p, int *w);
void cdb(char *s);
void clrin();
void clrn(char *n);
void cmax(int *p, int *pp);
void compwait();
void give(int *rx, int *tx);
void hassuit(int *p, int *strat, int tsuit, int suit);
void hud(int *n, int *e, int *p, int *w);
void init(int *n, int *e, int *p, int *w, int *deck, int *strat);
void ldb(int numPlayed);
void names(char *n, char *e , char* p, char *w, int name);
void out(char pos, int card, char* name, int n);
void passcards(int *n, int *e, int *p, int *w, int pass);
void phud(int *p);
void ppass(int *p, int *pp, int w);
void printplayers(int *trick, char *nname, char *ename, char *pname, char *wname);
void qdb(char *s);
void sdb(char *s);
void shuf(int *deck);
void sort(int *p);
void tdb(int *trick);

